# Generated by Django 2.2.6 on 2019-12-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('book_desctiption', models.TextField()),
                ('book_url_image', models.CharField(max_length=1000)),
                ('book_year', models.DateField()),
                ('book_price', models.CharField(max_length=100)),
                ('book_publisher', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('user_surname', models.CharField(default='UNKNOWN', max_length=64)),
                ('user_login', models.CharField(max_length=64)),
                ('user_password', models.CharField(default='qwe123ASD', max_length=64)),
                ('user_url_image', models.CharField(default='mainapp\\images\\defaultuser.png', max_length=1000)),
                ('user_role', models.CharField(default='user', max_length=32)),
                ('user_status', models.CharField(default='not banned', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=100)),
                ('chapter', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manga_comics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manga_comics_name', models.CharField(max_length=100)),
                ('manga_comics_desctiption', models.TextField()),
                ('manga_url_image', models.CharField(max_length=1000)),
                ('manga_comics_year', models.DateField()),
                ('manga_comics_price', models.CharField(max_length=100)),
                ('manga_comics_categories', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category')),
                ('manga_comics_volume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Volume')),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazine_name', models.CharField(max_length=100)),
                ('magazine_year', models.DateField()),
                ('magazine_url_image', models.CharField(max_length=1000)),
                ('magazine_chapter', models.CharField(max_length=100)),
                ('magazine_price', models.CharField(max_length=100)),
                ('magazine_categories', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category')),
                ('magazine_country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite_manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_manga', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Manga_comics')),
                ('favorite_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite_magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_magazine', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Magazine')),
                ('favorite_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Book')),
                ('favorite_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.User')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_categories',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Country'),
        ),
    ]
