# Generated by Django 2.2.6 on 2019-12-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_order_by_parameter',
            field=models.CharField(choices=[('book_main_rating', 'book_main_rating'), ('book_critics_raing', 'book_critics_raing'), ('book_user_rating', 'book_user_rating'), ('book_date', 'book_date')], default='movie_main_rating', max_length=32),
        ),
    ]
