# Generated by Django 2.2.6 on 2019-12-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_category_category_order_by_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_user_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
