# Generated by Django 2.2.6 on 2019-12-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_book_book_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_critics_raing',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='book',
            name='book_main_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_order_by_parameter',
            field=models.CharField(choices=[('book_main_rating', 'book_main_rating'), ('book_critics_raing', 'book_critics_raing'), ('book_user_rating', 'book_user_rating'), ('book_year', 'book_year')], default='book_main_rating', max_length=32),
        ),
    ]
