# Generated by Django 2.2.6 on 2019-12-12 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20191212_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cod',
            field=models.CharField(default=datetime.datetime(2019, 12, 12, 9, 54, 39, 374410, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
